language: node_js
node_js:
  - "iojs"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "node"

os:
  - linux
  - osx
dist: trusty
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - node_js: "iojs"
    - node_js: "0.10"
    - node_js: "0.11"
    - node_js: "0.12"
    - node_js: "4"

cache:
  directories:
    - "node_modules"

install:
  - node --version
  - npm --version
  - git --version
  - npm install

after_success:
  - npm install -g codecov
  - codecov
